Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,23 +16,27 @@ jobs:
       - run:
           name: Execute Downloads.bat
           command: |
-            $username = "Sachith"
-            $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
-            
-            # Check if the user already exists
-            $userExists = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
-            if ($userExists -eq $null) {
-                # User does not exist, so create it
-                New-LocalUser -Name $username -Password $password -FullName "Runner Admin" -Description       "CircleCI Runner Admin" -AccountNeverExpires
-            } else {
-                Write-Host "User $username already exists."
-            }
-            
-            # Set the password
-            Set-LocalUser -Name $username -Password $password
+           # Create User Sachith
+          echo "Checking if user 'Sachith' exists before creating..."
+          $existingUser = Get-LocalUser -Name 'Sachith' -ErrorAction SilentlyContinue
+          if ($existingUser) {
+              echo "User 'Sachith' already exists."
+          } else {
+              echo "User 'Sachith' does not exist or an error occurred."
+              try {
+                  $password = ConvertTo-SecureString "Sachith@12345" -AsPlainText -Force
+                  $userCreationOutput = New-LocalUser -Name 'Sachith' -Password $password -PasswordNeverExpires:$true -AccountNeverExpires:$true
+                  echo "User 'Sachith' created successfully."
+                  Add-LocalGroupMember -Group 'Administrators' -Member 'Sachith'
+              } catch {
+                  echo "Error creating user 'Sachith': $_"
+                  exit 1
+              }
+          }
       - run:
           name: create tunnel
-          command: Invoke-Expression $env:crdauthcode
+          command: |
+          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AeaYSHAhvwx_jg75K7-9feJZw-w3rC1Q7uy0qxLg6tpMC9xIKx1zDt9F_QM44mMwXQAKJw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
       - run:
           name: Download loop
           command: |
